# Generated by Django 4.2.8 on 2023-12-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.TextField(default='0'),
        ),
    ]
