# Generated by Django 4.2.8 on 2023-12-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0002_pokemon_height_pokemon_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokeid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
