# Generated by Django 4.2.8 on 2023-12-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0003_pokemon_pokeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_experience',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprites',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stats',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.TextField(default='0'),
        ),
    ]
