# Generated by Django 4.2.8 on 2023-12-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0004_pokemon_abilities_pokemon_base_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='url_link',
            field=models.URLField(default='0'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokeid',
            field=models.TextField(default='0'),
        ),
    ]
