# Generated by Django 4.2.8 on 2023-12-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0005_remove_pokemon_abilities_remove_pokemon_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='url_link',
            field=models.URLField(default='https://play.pokemonshowdown.com/teambuilder'),
        ),
    ]
